"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import Link from "next/link";
import { Plus, RefreshCw, Upload } from "lucide-react";
import { bulkDeleteRecords, bulkDeleteZones, deleteRecord, deleteZone, getRecords, getSummary, getZone, getZones, importZoneFile, saveRecord, saveZone } from "@/lib/api";
import { DNSRecord, HostedZone, RecordPayload, ZonePayload } from "@/types/route53";
import { Layout } from "./Layout";
import { LoginForm } from "./LoginForm";
import { ConfirmModal, EditorModal, Toast } from "./Modals";
import { EmptyState, ErrorState, LoadingRows, RecordsTable, ZonesTable } from "./Tables";
import { useTheme } from "./ThemeProvider";

type ModalState = { kind: "zone" | "record"; zone?: HostedZone; record?: DNSRecord } | { kind: "delete-zone"; zone: HostedZone } | { kind: "delete-record"; record: DNSRecord } | { kind: "bulk-delete-zones" } | { kind: "bulk-delete-records" } | null;
type Notice = { text: string; error: boolean };
export function ConsoleApp() {
  const path = usePathname(); const router = useRouter(); const zoneId = Number(path.match(/^\/hosted-zones\/(\d+)\/?$/)?.[1]); const zoneRoute = Number.isFinite(zoneId) && zoneId > 0;
  const [ready, setReady] = useState(false), [signed, setSigned] = useState(false), [user, setUser] = useState("demo@route53.local"), [menu, setMenu] = useState(false);
  const { dark, toggleTheme } = useTheme();
  const [zones, setZones] = useState<HostedZone[]>([]), [zoneTotal, setZoneTotal] = useState(0), [zoneSearch, setZoneSearch] = useState(""), [zonePage, setZonePage] = useState(1);
  const [activeZone, setActiveZone] = useState<HostedZone | null>(null), [loadedZoneId, setLoadedZoneId] = useState(0), [records, setRecords] = useState<DNSRecord[]>([]), [recordTotal, setRecordTotal] = useState(0), [recordSearch, setRecordSearch] = useState(""), [recordFilter, setRecordFilter] = useState(""), [recordPage, setRecordPage] = useState(1);
  const [summary, setSummary] = useState({ hosted_zones: 0, dns_records: 0 }), [loadingZones, setLoadingZones] = useState(true), [loadingRecords, setLoadingRecords] = useState(false), [zoneError, setZoneError] = useState(""), [recordError, setRecordError] = useState(""), [detailError, setDetailError] = useState("");
  const [modal, setModal] = useState<ModalState>(null), [saving, setSaving] = useState(false), [deleting, setDeleting] = useState(false), [notice, setNotice] = useState<Notice | null>(null);
  const [importing, setImporting] = useState(false);
  const [selectedZones, setSelectedZones] = useState<Set<number>>(new Set());
  const [selectedRecords, setSelectedRecords] = useState<Set<number>>(new Set());
  const importInputRef = useRef<HTMLInputElement | null>(null);
  const notify = useCallback((text: string, error = false) => { setNotice({ text, error }); window.setTimeout(() => setNotice(null), 4000); }, []);
  useEffect(() => { queueMicrotask(() => { try { const session = localStorage.getItem("route53-session"); if (session) { const value = JSON.parse(session); if (typeof value.user === "string") setUser(value.user); setSigned(true); } } catch { localStorage.removeItem("route53-session"); } setReady(true); }); }, []);

  const refreshSummary = useCallback(async () => { setSummary(await getSummary()); }, []);
  const refreshZones = useCallback(async () => { setLoadingZones(true); setZoneError(""); try { const result = await getZones(zoneSearch, zonePage); setZones(result.items); setZoneTotal(result.total); await refreshSummary(); } catch (error) { setZoneError((error as Error).message); } finally { setLoadingZones(false); } }, [zoneSearch, zonePage, refreshSummary]);
  const refreshRecords = useCallback(async () => { if (!zoneRoute) return; setLoadingRecords(true); setRecordError(""); try { const result = await getRecords(zoneId, recordSearch, recordFilter, recordPage); setRecords(result.items); setRecordTotal(result.total); await refreshSummary(); } catch (error) { setRecordError((error as Error).message); } finally { setLoadingRecords(false); } }, [zoneRoute, zoneId, recordSearch, recordFilter, recordPage, refreshSummary]);
  useEffect(() => { if (!ready || !signed) return; const timer = window.setTimeout(() => void refreshZones(), 0); return () => window.clearTimeout(timer); }, [ready, signed, refreshZones]);
  useEffect(() => { if (!ready || !signed || !zoneRoute) return; let current = true; getZone(zoneId).then(value => { if (current) { setActiveZone(value); setLoadedZoneId(zoneId); setDetailError(""); } }).catch(error => { if (current) { setDetailError((error as Error).message); notify((error as Error).message, true); } }); return () => { current = false; }; }, [ready, signed, zoneRoute, zoneId, notify]);
  useEffect(() => { if (!ready || !signed || !zoneRoute) return; const timer = window.setTimeout(() => void refreshRecords(), 0); return () => window.clearTimeout(timer); }, [ready, signed, refreshRecords, zoneRoute]);
  useEffect(() => { setSelectedZones(new Set()); }, [zones]);
  useEffect(() => { setSelectedRecords(new Set()); }, [records]);
  const title = useMemo(() => zoneRoute ? (loadedZoneId === zoneId ? activeZone?.name || "Hosted zone" : "Hosted zone") : path === "/hosted-zones" ? "Hosted zones" : path === "/" ? "Route 53" : ({ "/traffic-policies": "Traffic policies", "/health-checks": "Health checks", "/resolver": "Resolver", "/profiles": "Profiles" } as Record<string, string>)[path] || "Route 53", [zoneRoute, zoneId, loadedZoneId, activeZone, path]);
  useEffect(() => {
    function onKeyDown(event: KeyboardEvent) {
      const target = event.target as HTMLElement | null;
      const typing = target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA" || target.isContentEditable);
      if (event.key === "Escape" && modal) { setModal(null); return; }
      if (typing) return;
      if (event.key === "n" && (path === "/hosted-zones" || zoneRoute)) { event.preventDefault(); setModal(zoneRoute ? { kind: "record" } : { kind: "zone" }); }
    }
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [modal, path, zoneRoute]);
  if (!ready) return <main className="boot-screen"><span className="spinner"/>Loading Route 53 console…</main>;
  if (!signed) return <LoginForm onLogin={email => { setUser(email); setSigned(true); }}/>

  async function submitZone(payload: ZonePayload) { setSaving(true); try { await saveZone(payload, modal?.kind === "zone" ? modal.zone?.id : undefined); setModal(null); notify(modal?.kind === "zone" && modal.zone ? "Hosted zone updated" : "Hosted zone created"); if (!modal || modal.kind !== "zone" || !modal.zone) { setZoneSearch(""); setZonePage(1); const result = await getZones("", 1); setZones(result.items); setZoneTotal(result.total); await refreshSummary(); } else await refreshZones(); } catch (error) { notify((error as Error).message, true); } finally { setSaving(false); } }
  async function submitRecord(payload: RecordPayload) { if (!zoneRoute) return; setSaving(true); try { await saveRecord(payload, zoneId, modal?.kind === "record" ? modal.record?.id : undefined); setModal(null); notify(modal?.kind === "record" && modal.record ? "DNS record updated" : "DNS record created"); setRecordPage(1); await refreshRecords(); } catch (error) { notify((error as Error).message, true); } finally { setSaving(false); } }
  async function confirmDelete() { if (!modal || (modal.kind !== "delete-zone" && modal.kind !== "delete-record" && modal.kind !== "bulk-delete-zones" && modal.kind !== "bulk-delete-records")) return; setDeleting(true); try { if (modal.kind === "delete-zone") { await deleteZone(modal.zone.id); setModal(null); notify("Hosted zone deleted"); if (zoneRoute) router.push("/hosted-zones"); await refreshZones(); } else if (modal.kind === "delete-record") { await deleteRecord(modal.record.id); setModal(null); notify("DNS record deleted"); await refreshRecords(); } else if (modal.kind === "bulk-delete-zones") { const result = await bulkDeleteZones([...selectedZones]); setModal(null); setSelectedZones(new Set()); notify(`Deleted ${result.deleted} hosted zone(s)`); await refreshZones(); } else { const result = await bulkDeleteRecords([...selectedRecords]); setModal(null); setSelectedRecords(new Set()); notify(`Deleted ${result.deleted} record(s)`); await refreshRecords(); } } catch (error) { notify((error as Error).message, true); } finally { setDeleting(false); } }
  function toggleZoneSelect(id: number) { setSelectedZones(prev => { const next = new Set(prev); next.has(id) ? next.delete(id) : next.add(id); return next; }); }
  function toggleZoneSelectAll(ids: number[]) { setSelectedZones(prev => { const allSelected = ids.every(id => prev.has(id)); const next = new Set(prev); ids.forEach(id => allSelected ? next.delete(id) : next.add(id)); return next; }); }
  function toggleRecordSelect(id: number) { setSelectedRecords(prev => { const next = new Set(prev); next.has(id) ? next.delete(id) : next.add(id); return next; }); }
  function toggleRecordSelectAll(ids: number[]) { setSelectedRecords(prev => { const allSelected = ids.every(id => prev.has(id)); const next = new Set(prev); ids.forEach(id => allSelected ? next.delete(id) : next.add(id)); return next; }); }
  async function exportZone(format: "json" | "bind") { try { const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api"}/zones/${zoneId}/export?format=${format}`); if (!response.ok) throw new Error(`Export failed (${response.status})`); const data = format === "json" ? JSON.stringify(await response.json(), null, 2) : await response.text(); const blob = new Blob([data], { type: format === "json" ? "application/json" : "text/dns" }); const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(blob); anchor.download = `${activeZone?.name || "hosted-zone"}.${format === "json" ? "json" : "zone"}`; anchor.click(); URL.revokeObjectURL(anchor.href); notify(`Hosted zone exported as ${format.toUpperCase()}`); } catch (error) { notify((error as Error).message, true); } }
  function logoutClick() { localStorage.removeItem("route53-session"); setSigned(false); setActiveZone(null); router.push("/"); }
  async function importFile(file: File) { setImporting(true); try { const content = await file.text(); const result = await importZoneFile(zoneId, content); notify(result.skipped.length ? `Imported ${result.imported} record(s); skipped ${result.skipped.length} unrecognized line(s)` : `Imported ${result.imported} record(s)`); setRecordPage(1); await refreshRecords(); } catch (error) { notify((error as Error).message, true); } finally { setImporting(false); if (importInputRef.current) importInputRef.current.value = ""; } }

  const isComingSoon = ["/traffic-policies", "/health-checks", "/resolver", "/profiles"].includes(path);
  return <><Layout path={path} title={title} user={user} dark={dark} menuOpen={menu} onMenu={() => setMenu(v => !v)} onLogout={logoutClick} onToggleTheme={toggleTheme}>
    {path === "/" && <Dashboard summary={summary} loading={loadingZones} error={zoneError} onRetry={() => void refreshZones()} onCreate={() => setModal({ kind: "zone" })}/>} 
    {path === "/hosted-zones" && <><div className="title-row"><div><h1>Hosted zones</h1><div className="desc">A hosted zone is a container for records for a domain.</div></div><button className="btn primary" onClick={() => setModal({ kind: "zone" })}><Plus size={15}/> Create hosted zone</button></div>{zoneError ? <ErrorState message={zoneError} retry={() => void refreshZones()}/> : <ZonesTable zones={zones} total={zoneTotal} page={zonePage} search={zoneSearch} loading={loadingZones} selected={selectedZones} onSearch={v => { setZoneSearch(v); setZonePage(1); }} onPage={setZonePage} onRefresh={() => void refreshZones()} onOpen={z => router.push(`/hosted-zones/${z.id}`)} onEdit={z => setModal({ kind: "zone", zone: z })} onDelete={z => setModal({ kind: "delete-zone", zone: z })} onToggleSelect={toggleZoneSelect} onToggleSelectAll={toggleZoneSelectAll} onBulkDelete={() => setModal({ kind: "bulk-delete-zones" })}/>}</>}
    {zoneRoute && <>{detailError ? <ErrorState message={detailError} retry={() => { setDetailError(""); getZone(zoneId).then(value => { setActiveZone(value); setLoadedZoneId(zoneId); }).catch(error => setDetailError((error as Error).message)); }}/> : activeZone && loadedZoneId === zoneId ? <><div className="title-row"><div><h1>{activeZone.name}</h1><div className="desc">Hosted zone ID: <span className="mono">Z{String(activeZone.id).padStart(10, "0")}</span>　·　{activeZone.is_private ? "Private hosted zone" : "Public hosted zone"}</div></div><div className="title-actions"><input ref={importInputRef} type="file" accept=".txt,.zone,.bind,text/plain" hidden onChange={e => { const file = e.target.files?.[0]; if (file) void importFile(file); }}/><button className="btn" disabled={importing} onClick={() => importInputRef.current?.click()}><Upload size={15}/> {importing ? "Importing…" : "Import BIND"}</button><button className="btn" onClick={() => void exportZone("json")}>Export JSON</button><button className="btn" onClick={() => void exportZone("bind")}>Export BIND</button><button className="btn primary" onClick={() => setModal({ kind: "record" })}><Plus size={15}/> Create record</button></div></div><div className="zone-meta card"><span><b>Hosted zone ID</b><br/><span className="mono">Z{String(activeZone.id).padStart(10, "0")}</span></span><span><b>Created</b><br/>{formatDate(activeZone.created_at)}</span><span><b>Record count</b><br/>{activeZone.record_count ?? recordTotal}</span><span><b>Comment</b><br/>{activeZone.comment || "—"}</span></div>{recordError ? <ErrorState message={recordError} retry={() => void refreshRecords()}/> : <RecordsTable records={records} total={recordTotal} page={recordPage} search={recordSearch} filter={recordFilter} loading={loadingRecords} selected={selectedRecords} onSearch={v => { setRecordSearch(v); setRecordPage(1); }} onFilter={v => { setRecordFilter(v); setRecordPage(1); }} onPage={setRecordPage} onRefresh={() => void refreshRecords()} onEdit={record => setModal({ kind: "record", record })} onDelete={record => setModal({ kind: "delete-record", record })} onToggleSelect={toggleRecordSelect} onToggleSelectAll={toggleRecordSelectAll} onBulkDelete={() => setModal({ kind: "bulk-delete-records" })}/>}</> : <section className="card"><LoadingRows columns={4}/></section>}</>}
    {isComingSoon && <><div className="title-row"><div><h1>{title}</h1><div className="desc">Route 53 {title.toLowerCase()} configuration.</div></div></div><section className="card empty"><div className="coming-soon-mark">AWS</div><h3>{title} is coming soon</h3><p className="desc">This section is part of the Route 53 console and will be available in a future release.</p><Link href="/" className="btn">Back to dashboard</Link></section></>}
    {path !== "/" && path !== "/hosted-zones" && !zoneRoute && !isComingSoon && <section className="card"><EmptyState title="Page not found" text="Use the Route 53 navigation to open an available page."/></section>}
  </Layout>
  {notice && <Toast error={notice.error}>{notice.text}</Toast>}
  {modal?.kind === "zone" && <EditorModal kind="zone" zone={modal.zone} busy={saving} onClose={() => setModal(null)} onZone={submitZone} onRecord={submitRecord}/>}
  {modal?.kind === "record" && <EditorModal kind="record" record={modal.record} busy={saving} onClose={() => setModal(null)} onZone={submitZone} onRecord={submitRecord}/>}
  {modal?.kind === "delete-zone" && <ConfirmModal title="Delete hosted zone?" description={`Delete hosted zone ${modal.zone.name} and all of its DNS records? This action cannot be undone.`} onCancel={() => setModal(null)} onConfirm={() => void confirmDelete()} busy={deleting}/>}
  {modal?.kind === "delete-record" && <ConfirmModal title="Delete record?" description={`Delete ${modal.record.name} (${modal.record.type})? This action cannot be undone.`} onCancel={() => setModal(null)} onConfirm={() => void confirmDelete()} busy={deleting}/>}
  {modal?.kind === "bulk-delete-zones" && <ConfirmModal title="Delete hosted zones?" description={`Delete ${selectedZones.size} selected hosted zone(s) and all of their DNS records? This action cannot be undone.`} onCancel={() => setModal(null)} onConfirm={() => void confirmDelete()} busy={deleting}/>}
  {modal?.kind === "bulk-delete-records" && <ConfirmModal title="Delete records?" description={`Delete ${selectedRecords.size} selected record(s)? This action cannot be undone.`} onCancel={() => setModal(null)} onConfirm={() => void confirmDelete()} busy={deleting}/>}
  </>;
}

function Dashboard({ summary, loading, error, onRetry, onCreate }: { summary: { hosted_zones: number; dns_records: number }; loading: boolean; error: string; onRetry: () => void; onCreate: () => void }) {
  return <><div className="title-row"><div><h1>Amazon Route 53</h1><div className="desc">A highly available and scalable cloud Domain Name System (DNS) web service.</div></div><button className="btn" onClick={onRetry} disabled={loading}><RefreshCw size={15}/> Refresh</button></div>{error && <ErrorState message={error} retry={onRetry}/>}<div className="stats"><Link className="stat stat-link" href="/hosted-zones"><span className="stat-label">Hosted zones</span><strong>{loading ? "…" : summary.hosted_zones}</strong><span className="link">View hosted zones →</span></Link><div className="stat"><span className="stat-label">DNS records</span><strong>{loading ? "…" : summary.dns_records}</strong><span className="muted">Across your hosted zones</span></div><div className="stat"><span className="stat-label">Service health</span><strong className="service-ok">● Operational</strong><span className="muted">All demonstration services are available</span></div></div><section className="card dashboard-start"><h2>Get started with Route 53</h2><p className="desc">Create a hosted zone to manage DNS routing for a domain, then add records to control where traffic is sent.</p><button className="btn primary" onClick={onCreate}><Plus size={15}/> Create hosted zone</button></section><section className="card"><h2>Route 53 features</h2><div className="feature-grid">{[["Traffic policies", "/traffic-policies", "Route traffic using configurable routing policies."], ["Health checks", "/health-checks", "Monitor the availability of your endpoints."], ["Resolver", "/resolver", "Manage DNS resolution for your networks."]].map(([name, href, text]) => <article className="feature-card" key={href}><b>{name}</b><p className="desc">{text}</p><Link className="link" href={href}>Learn more →</Link></article>)}</div></section></>;
}
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "—" : new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(date); }
