"use client";
import { FormEvent, useState } from "react";
import { DNSRecord, HostedZone, RECORD_TYPES, RecordPayload, ZonePayload } from "@/types/route53";

const hints: Record<string, { placeholder: string; help: string }> = {
  A: { placeholder: "192.0.2.1", help: "IPv4 address. Add one address per line." }, AAAA: { placeholder: "2001:db8::1", help: "IPv6 address. Add one address per line." },
  CNAME: { placeholder: "target.example.com.", help: "Canonical DNS name. CNAME cannot coexist with other data at the same name." }, TXT: { placeholder: '"v=spf1 include:example.com ~all"', help: "Text value. Add one string per line; quote strings containing spaces." },
  MX: { placeholder: "10 mail.example.com.", help: "One mail exchanger per line: priority hostname." }, NS: { placeholder: "ns1.example.com.", help: "Name server hostname. Add one server per line." }, PTR: { placeholder: "host.example.com.", help: "Reverse lookup target hostname." },
  SRV: { placeholder: "10 5 5060 sip.example.com.", help: "One service per line: priority weight port target." }, CAA: { placeholder: '0 issue "letsencrypt.org"', help: "One policy per line: flags tag value. Tags include issue, issuewild, and iodef." },
  SOA: { placeholder: "ns-100.awsdns-12.com. hostmaster.example.com. 1 7200 900 1209600 86400", help: "Start of authority fields: mname rname serial refresh retry expire minimum." },
};
export function ZoneForm({ value, busy, onCancel, onSubmit }: { value?: HostedZone; busy: boolean; onCancel: () => void; onSubmit: (payload: ZonePayload) => void }) {
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); onSubmit({ name: String(f.get("name")), comment: String(f.get("comment")), is_private: f.get("is_private") === "on" }); }
  return <form onSubmit={submit}><p className="desc modal-intro">Create a hosted zone to manage DNS routing for a domain.</p><div className="formrow"><label htmlFor="zone-name">Domain name *</label><input id="zone-name" className="field" name="name" required maxLength={253} placeholder="example.com" defaultValue={value?.name}/><small>Enter a fully qualified domain name.</small></div><div className="formrow"><label htmlFor="zone-kind">Type</label><select id="zone-kind" className="field" name="is_private" defaultValue={value?.is_private ? "on" : "off"}><option value="off">Public hosted zone</option><option value="on">Private hosted zone</option></select></div><div className="formrow"><label htmlFor="zone-comment">Comment</label><textarea id="zone-comment" className="field" name="comment" rows={3} maxLength={500} defaultValue={value?.comment}/></div><FormActions busy={busy} onCancel={onCancel} submit={value ? "Save changes" : "Create hosted zone"}/></form>;
}
export function RecordForm({ value, busy, onCancel, onSubmit }: { value?: DNSRecord; busy: boolean; onCancel: () => void; onSubmit: (payload: RecordPayload) => void }) {
  const [type, setType] = useState<string>(value?.type || "A"); const hint = hints[type];
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); onSubmit({ name: String(f.get("name")), type: String(f.get("type")) as RecordPayload["type"], value: String(f.get("value")), ttl: Number(f.get("ttl")), routing_policy: String(f.get("routing_policy")) }); }
  return <form onSubmit={submit}><div className="formrow"><label htmlFor="record-name">Record name *</label><input id="record-name" className="field" name="name" required maxLength={253} placeholder="www.example.com" defaultValue={value?.name}/><small>Enter a fully qualified record name, including the zone name.</small></div><div className="formrow"><label htmlFor="record-type">Record type *</label><select id="record-type" className="field" name="type" value={type} onChange={e => setType(e.target.value)}>{RECORD_TYPES.map(t => <option key={t} value={t}>{t}{t === "SOA" ? " (zone authority)" : ""}</option>)}</select></div><div className="formrow"><label htmlFor="record-value">{type === "TXT" ? "Value / text" : "Value"} *</label><textarea id="record-value" className="field record-value" name="value" required maxLength={4096} rows={3} placeholder={hint.placeholder} defaultValue={value?.value}/><small>{hint.help}</small></div><div className="formrow"><label htmlFor="record-ttl">TTL (seconds)</label><input id="record-ttl" className="field" name="ttl" type="number" min={1} max={2147483647} required defaultValue={value?.ttl || 300}/></div><div className="formrow"><label htmlFor="record-policy">Routing policy</label><select id="record-policy" className="field" name="routing_policy" defaultValue={value?.routing_policy || "Simple"}>{["Simple", "Weighted", "Latency", "Failover", "Geolocation", "Multivalue answer"].map(p => <option key={p}>{p}</option>)}</select></div><FormActions busy={busy} onCancel={onCancel} submit={value ? "Save changes" : "Create record"}/></form>;
}
function FormActions({ busy, onCancel, submit }: { busy: boolean; onCancel: () => void; submit: string }) { return <div className="form-actions"><button type="button" className="btn" onClick={onCancel}>Cancel</button><button className="btn primary" disabled={busy}>{busy ? "Saving…" : submit}</button></div>; }
