"use client";
import { Edit2, ExternalLink, RefreshCw, Search, Trash2 } from "lucide-react";
import { DNSRecord, HostedZone } from "@/types/route53";
import { Pagination } from "./Pagination";

export function ZonesTable({ zones, total, page, search, loading, selected, onSearch, onPage, onRefresh, onOpen, onEdit, onDelete, onToggleSelect, onToggleSelectAll, onBulkDelete }: { zones: HostedZone[]; total: number; page: number; search: string; loading: boolean; selected: Set<number>; onSearch: (value: string) => void; onPage: (page: number) => void; onRefresh: () => void; onOpen: (zone: HostedZone) => void; onEdit: (zone: HostedZone) => void; onDelete: (zone: HostedZone) => void; onToggleSelect: (id: number) => void; onToggleSelectAll: (ids: number[]) => void; onBulkDelete: () => void }) {
  const allSelected = zones.length > 0 && zones.every(z => selected.has(z.id));
  return <section className="card"><div className="section-title"><div><h2>Hosted zones <span className="muted">({total})</span></h2><p className="desc">Manage DNS for your domains.</p></div><button className="btn" onClick={onRefresh} disabled={loading}><RefreshCw size={15}/> Refresh</button></div><div className="toolbar"><label className="searchbox"><Search size={16}/><input className="field" aria-label="Search hosted zones" placeholder="Search by domain name or comment" value={search} onChange={e => onSearch(e.target.value)}/></label></div>
    {selected.size > 0 && <div className="bulk-bar"><span>{selected.size} selected</span><button className="btn danger-text" onClick={onBulkDelete}><Trash2 size={15}/> Delete selected</button></div>}
    {loading ? <LoadingRows columns={6}/> : zones.length ? <><div className="tablewrap"><table><thead><tr><th className="select-col"><input type="checkbox" aria-label="Select all hosted zones on this page" checked={allSelected} onChange={() => onToggleSelectAll(zones.map(z => z.id))}/></th><th>Domain name</th><th>Hosted zone ID</th><th>Type</th><th>Records</th><th>Created</th><th>Actions</th></tr></thead><tbody>{zones.map(z => <tr key={z.id} className={selected.has(z.id) ? "row-selected" : undefined}><td className="select-col"><input type="checkbox" aria-label={`Select ${z.name}`} checked={selected.has(z.id)} onChange={() => onToggleSelect(z.id)}/></td><td><button className="table-link" onClick={() => onOpen(z)}>{z.name}</button>{z.comment && <small className="table-subtitle">{z.comment}</small>}</td><td className="mono">Z{String(z.id).padStart(10, "0")}</td><td>{z.is_private ? "Private hosted zone" : "Public hosted zone"}</td><td>{z.record_count}</td><td>{dateTime(z.created_at)}</td><td className="actions"><button className="icon-action" title="Open zone" onClick={() => onOpen(z)}><ExternalLink size={15}/></button><button className="icon-action" title="Edit zone" onClick={() => onEdit(z)}><Edit2 size={15}/></button><button className="icon-action danger-text" title="Delete zone" onClick={() => onDelete(z)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div><Pagination page={page} total={total} onChange={onPage}/></> : <EmptyState title={search ? "No hosted zones match your search" : "No hosted zones"} text={search ? "Try another domain or comment." : "Create a hosted zone to start managing DNS."}/>}</section>;
}
export function RecordsTable({ records, total, page, search, filter, loading, selected, onSearch, onFilter, onPage, onRefresh, onEdit, onDelete, onToggleSelect, onToggleSelectAll, onBulkDelete }: { records: DNSRecord[]; total: number; page: number; search: string; filter: string; loading: boolean; selected: Set<number>; onSearch: (v: string) => void; onFilter: (v: string) => void; onPage: (p: number) => void; onRefresh: () => void; onEdit: (r: DNSRecord) => void; onDelete: (r: DNSRecord) => void; onToggleSelect: (id: number) => void; onToggleSelectAll: (ids: number[]) => void; onBulkDelete: () => void }) {
  const allSelected = records.length > 0 && records.every(r => selected.has(r.id));
  return <section className="card"><div className="section-title"><div><h2>Records <span className="muted">({total})</span></h2><p className="desc">DNS records associated with this hosted zone.</p></div><button className="btn" onClick={onRefresh} disabled={loading}><RefreshCw size={15}/> Refresh</button></div><div className="toolbar"><label className="searchbox"><Search size={16}/><input className="field" aria-label="Search records" placeholder="Search by record name or value" value={search} onChange={e => onSearch(e.target.value)}/></label><select className="field filter-select" aria-label="Filter by record type" value={filter} onChange={e => onFilter(e.target.value)}><option value="">All record types</option>{["A", "AAAA", "CNAME", "TXT", "MX", "NS", "PTR", "SRV", "CAA", "SOA"].map(t => <option key={t}>{t}</option>)}</select></div>
    {selected.size > 0 && <div className="bulk-bar"><span>{selected.size} selected</span><button className="btn danger-text" onClick={onBulkDelete}><Trash2 size={15}/> Delete selected</button></div>}
    {loading ? <LoadingRows columns={6}/> : records.length ? <><div className="tablewrap"><table><thead><tr><th className="select-col"><input type="checkbox" aria-label="Select all records on this page" checked={allSelected} onChange={() => onToggleSelectAll(records.map(r => r.id))}/></th><th>Record name</th><th>Type</th><th>Value / Route traffic to</th><th>TTL (seconds)</th><th>Routing policy</th><th>Actions</th></tr></thead><tbody>{records.map(r => <tr key={r.id} className={selected.has(r.id) ? "row-selected" : undefined}><td className="select-col"><input type="checkbox" aria-label={`Select ${r.name} ${r.type}`} checked={selected.has(r.id)} onChange={() => onToggleSelect(r.id)}/></td><td className="record-name">{r.name}</td><td><span className="pill">{r.type}</span></td><td className="record-value-cell">{r.value.split("\n").map((v, i) => <span key={i}>{v}</span>)}</td><td>{r.ttl}</td><td>{r.routing_policy}</td><td className="actions"><button className="icon-action" title="Edit record" onClick={() => onEdit(r)}><Edit2 size={15}/></button><button className="icon-action danger-text" title="Delete record" onClick={() => onDelete(r)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div><Pagination page={page} total={total} onChange={onPage}/></> : <EmptyState title={search || filter ? "No records match your filters" : "No records in this hosted zone"} text={search || filter ? "Clear or update the search and record type filter." : "Create a DNS record to get started."}/>}</section>;
}
export function LoadingRows({ columns = 5 }: { columns?: number }) { return <div className="loading-state" role="status" aria-label="Loading"><span className="spinner"/>Loading…<div className="skeleton-table">{Array.from({ length: 4 }, (_, i) => <div key={i} style={{ gridTemplateColumns: `repeat(${columns}, 1fr)` }}>{Array.from({ length: columns }, (_, j) => <i key={j}/>)}</div>)}</div></div>; }
export function EmptyState({ title, text }: { title: string; text: string }) { return <div className="empty"><h3>{title}</h3><p className="muted">{text}</p></div>; }
export function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="inline-error" role="alert"><span>{message}</span><button className="btn" onClick={retry}>Try again</button></div>; }
function dateTime(value?: string) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.valueOf()) ? "—" : new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(date); }
